// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mycqrs.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestResponse_StatusEnum int32

const (
	RequestResponse_OK    RequestResponse_StatusEnum = 0
	RequestResponse_ERROR RequestResponse_StatusEnum = 1
)

var RequestResponse_StatusEnum_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}

var RequestResponse_StatusEnum_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x RequestResponse_StatusEnum) String() string {
	return proto.EnumName(RequestResponse_StatusEnum_name, int32(x))
}

func (RequestResponse_StatusEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9cac780285d56342, []int{1, 0}
}

type Contact struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LastUpdated          *timestamp.Timestamp `protobuf:"bytes,5,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cac780285d56342, []int{0}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Contact) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Contact) GetLastUpdated() *timestamp.Timestamp {
	if m != nil {
		return m.LastUpdated
	}
	return nil
}

type RequestResponse struct {
	Status               RequestResponse_StatusEnum `protobuf:"varint,1,opt,name=status,proto3,enum=protocol.RequestResponse_StatusEnum" json:"status,omitempty"`
	Message              string                     `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *RequestResponse) Reset()         { *m = RequestResponse{} }
func (m *RequestResponse) String() string { return proto.CompactTextString(m) }
func (*RequestResponse) ProtoMessage()    {}
func (*RequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cac780285d56342, []int{1}
}

func (m *RequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestResponse.Unmarshal(m, b)
}
func (m *RequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestResponse.Marshal(b, m, deterministic)
}
func (m *RequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestResponse.Merge(m, src)
}
func (m *RequestResponse) XXX_Size() int {
	return xxx_messageInfo_RequestResponse.Size(m)
}
func (m *RequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RequestResponse proto.InternalMessageInfo

func (m *RequestResponse) GetStatus() RequestResponse_StatusEnum {
	if m != nil {
		return m.Status
	}
	return RequestResponse_OK
}

func (m *RequestResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ContactRequestResponse struct {
	Response             *RequestResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Contact              *Contact         `protobuf:"bytes,2,opt,name=contact,proto3" json:"contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ContactRequestResponse) Reset()         { *m = ContactRequestResponse{} }
func (m *ContactRequestResponse) String() string { return proto.CompactTextString(m) }
func (*ContactRequestResponse) ProtoMessage()    {}
func (*ContactRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cac780285d56342, []int{2}
}

func (m *ContactRequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactRequestResponse.Unmarshal(m, b)
}
func (m *ContactRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactRequestResponse.Marshal(b, m, deterministic)
}
func (m *ContactRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactRequestResponse.Merge(m, src)
}
func (m *ContactRequestResponse) XXX_Size() int {
	return xxx_messageInfo_ContactRequestResponse.Size(m)
}
func (m *ContactRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContactRequestResponse proto.InternalMessageInfo

func (m *ContactRequestResponse) GetResponse() *RequestResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *ContactRequestResponse) GetContact() *Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

type ContactArrayRequestResponse struct {
	Response             *RequestResponse `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	Contact              []*Contact       `protobuf:"bytes,2,rep,name=contact,proto3" json:"contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ContactArrayRequestResponse) Reset()         { *m = ContactArrayRequestResponse{} }
func (m *ContactArrayRequestResponse) String() string { return proto.CompactTextString(m) }
func (*ContactArrayRequestResponse) ProtoMessage()    {}
func (*ContactArrayRequestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cac780285d56342, []int{3}
}

func (m *ContactArrayRequestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactArrayRequestResponse.Unmarshal(m, b)
}
func (m *ContactArrayRequestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactArrayRequestResponse.Marshal(b, m, deterministic)
}
func (m *ContactArrayRequestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactArrayRequestResponse.Merge(m, src)
}
func (m *ContactArrayRequestResponse) XXX_Size() int {
	return xxx_messageInfo_ContactArrayRequestResponse.Size(m)
}
func (m *ContactArrayRequestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactArrayRequestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContactArrayRequestResponse proto.InternalMessageInfo

func (m *ContactArrayRequestResponse) GetResponse() *RequestResponse {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *ContactArrayRequestResponse) GetContact() []*Contact {
	if m != nil {
		return m.Contact
	}
	return nil
}

type ContactReference struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContactReference) Reset()         { *m = ContactReference{} }
func (m *ContactReference) String() string { return proto.CompactTextString(m) }
func (*ContactReference) ProtoMessage()    {}
func (*ContactReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cac780285d56342, []int{4}
}

func (m *ContactReference) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContactReference.Unmarshal(m, b)
}
func (m *ContactReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContactReference.Marshal(b, m, deterministic)
}
func (m *ContactReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContactReference.Merge(m, src)
}
func (m *ContactReference) XXX_Size() int {
	return xxx_messageInfo_ContactReference.Size(m)
}
func (m *ContactReference) XXX_DiscardUnknown() {
	xxx_messageInfo_ContactReference.DiscardUnknown(m)
}

var xxx_messageInfo_ContactReference proto.InternalMessageInfo

func (m *ContactReference) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ListContactsFilter struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListContactsFilter) Reset()         { *m = ListContactsFilter{} }
func (m *ListContactsFilter) String() string { return proto.CompactTextString(m) }
func (*ListContactsFilter) ProtoMessage()    {}
func (*ListContactsFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_9cac780285d56342, []int{5}
}

func (m *ListContactsFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContactsFilter.Unmarshal(m, b)
}
func (m *ListContactsFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContactsFilter.Marshal(b, m, deterministic)
}
func (m *ListContactsFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContactsFilter.Merge(m, src)
}
func (m *ListContactsFilter) XXX_Size() int {
	return xxx_messageInfo_ListContactsFilter.Size(m)
}
func (m *ListContactsFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContactsFilter.DiscardUnknown(m)
}

var xxx_messageInfo_ListContactsFilter proto.InternalMessageInfo

func (m *ListContactsFilter) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterEnum("protocol.RequestResponse_StatusEnum", RequestResponse_StatusEnum_name, RequestResponse_StatusEnum_value)
	proto.RegisterType((*Contact)(nil), "protocol.Contact")
	proto.RegisterType((*RequestResponse)(nil), "protocol.RequestResponse")
	proto.RegisterType((*ContactRequestResponse)(nil), "protocol.ContactRequestResponse")
	proto.RegisterType((*ContactArrayRequestResponse)(nil), "protocol.ContactArrayRequestResponse")
	proto.RegisterType((*ContactReference)(nil), "protocol.ContactReference")
	proto.RegisterType((*ListContactsFilter)(nil), "protocol.ListContactsFilter")
}

func init() { proto.RegisterFile("mycqrs.proto", fileDescriptor_9cac780285d56342) }

var fileDescriptor_9cac780285d56342 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xb4, 0x92, 0x51, 0x6b, 0xd4, 0x40,
	0x10, 0xc7, 0x2f, 0xa7, 0xb9, 0x6b, 0x27, 0x77, 0xf5, 0x5c, 0x44, 0x62, 0x14, 0x5a, 0x16, 0x05,
	0x51, 0x48, 0x21, 0xe2, 0x5b, 0x45, 0x8a, 0x56, 0x05, 0x2b, 0x85, 0xd5, 0xe2, 0xa3, 0x6c, 0x93,
	0xe9, 0x11, 0x48, 0xb2, 0xe9, 0xee, 0xe6, 0xa1, 0xe0, 0x8b, 0xaf, 0x7e, 0x1e, 0x3f, 0x8c, 0x1f,
	0xc7, 0x74, 0x93, 0xbd, 0x48, 0x72, 0xa7, 0x22, 0xf4, 0x29, 0x9b, 0x99, 0xdf, 0xfc, 0xe7, 0x3f,
	0xc3, 0xc0, 0x2c, 0xbf, 0x8c, 0x2f, 0xa4, 0x0a, 0x4b, 0x29, 0xb4, 0x20, 0x5b, 0xe6, 0x13, 0x8b,
	0x2c, 0xd8, 0x5d, 0x0a, 0xb1, 0xcc, 0x70, 0xdf, 0x04, 0xce, 0xaa, 0xf3, 0x7d, 0x9d, 0xe6, 0xa8,
	0x34, 0xcf, 0xcb, 0x06, 0xa5, 0x19, 0x4c, 0x5f, 0x89, 0x42, 0xf3, 0x58, 0x93, 0x1d, 0x18, 0xa7,
	0x89, 0xef, 0xec, 0x39, 0x8f, 0xb7, 0x59, 0xfd, 0x22, 0x04, 0x6e, 0x16, 0x3c, 0x47, 0x7f, 0x6c,
	0x22, 0xe6, 0x4d, 0x5e, 0xc0, 0x2c, 0xe3, 0x4a, 0x7f, 0xa9, 0xca, 0x84, 0x6b, 0x4c, 0x7c, 0xb7,
	0xce, 0x79, 0x51, 0x10, 0x36, 0x6d, 0x42, 0xdb, 0x26, 0xfc, 0x64, 0xdb, 0x30, 0xef, 0x8a, 0x3f,
	0x6d, 0x70, 0xfa, 0xdd, 0x81, 0x5b, 0x0c, 0x2f, 0xaa, 0x3a, 0xc7, 0x50, 0x95, 0xa2, 0x50, 0x48,
	0x0e, 0x60, 0x52, 0x93, 0xba, 0x52, 0xa6, 0xf5, 0x4e, 0xf4, 0x30, 0xb4, 0xee, 0xc3, 0x1e, 0x1a,
	0x7e, 0x34, 0xdc, 0x51, 0x51, 0xe5, 0xac, 0xad, 0x21, 0x3e, 0x4c, 0x3f, 0xa0, 0x52, 0x7c, 0x69,
	0x7d, 0xda, 0x5f, 0xba, 0x0b, 0xd0, 0xf1, 0x64, 0x02, 0xe3, 0x93, 0xf7, 0x8b, 0x11, 0xd9, 0x06,
	0xf7, 0x88, 0xb1, 0x13, 0xb6, 0x70, 0xe8, 0x57, 0xb8, 0xdb, 0x8e, 0xde, 0xb7, 0xf4, 0x1c, 0xb6,
	0x64, 0xfb, 0x36, 0xa6, 0xbc, 0xe8, 0xde, 0x46, 0x53, 0x6c, 0x85, 0x92, 0xa7, 0x30, 0x8d, 0x1b,
	0x41, 0xe3, 0xc5, 0x8b, 0x6e, 0x77, 0x55, 0xb6, 0x93, 0x25, 0xe8, 0x37, 0x07, 0xee, 0xb7, 0xc1,
	0x43, 0x29, 0xf9, 0xe5, 0x75, 0x78, 0xb8, 0xf1, 0x17, 0x0f, 0x14, 0x16, 0xab, 0x0d, 0x9c, 0xa3,
	0xc4, 0x22, 0xc6, 0xfe, 0x15, 0xd0, 0x27, 0x40, 0x8e, 0x53, 0xa5, 0x5b, 0x4e, 0xbd, 0x49, 0x33,
	0x8d, 0x92, 0xdc, 0x01, 0x37, 0x16, 0x55, 0xa1, 0x0d, 0xe8, 0xb2, 0xe6, 0x27, 0xfa, 0xe9, 0xc0,
	0xbc, 0x05, 0x3f, 0xcb, 0xf4, 0x8a, 0x3b, 0x00, 0x38, 0x4c, 0x12, 0x7b, 0x61, 0x43, 0x2f, 0xc1,
	0xe6, 0xa1, 0xe8, 0x88, 0xbc, 0x84, 0x79, 0x73, 0x39, 0xff, 0x2b, 0xf0, 0x0e, 0xe6, 0xaf, 0x31,
	0xc3, 0x4e, 0x20, 0x18, 0x6e, 0xc3, 0x4e, 0xfe, 0x47, 0xa5, 0xe8, 0x47, 0x37, 0x1a, 0x43, 0x9e,
	0xd4, 0xa3, 0x1d, 0x03, 0xbc, 0x45, 0xfd, 0x2f, 0xc2, 0x7b, 0x6b, 0x72, 0x7d, 0xa7, 0xa7, 0x30,
	0xfb, 0x7d, 0xcd, 0xe4, 0x41, 0x57, 0x33, 0x5c, 0x7f, 0xf0, 0x68, 0xa0, 0xb8, 0xee, 0x86, 0xe8,
	0xe8, 0x6c, 0x62, 0xb8, 0x67, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0x0c, 0xe5, 0x53, 0x58, 0x20,
	0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ContactWriterClient is the client API for ContactWriter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContactWriterClient interface {
	AddContact(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*RequestResponse, error)
	UpdateContact(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*RequestResponse, error)
	DeleteContact(ctx context.Context, in *ContactReference, opts ...grpc.CallOption) (*RequestResponse, error)
}

type contactWriterClient struct {
	cc *grpc.ClientConn
}

func NewContactWriterClient(cc *grpc.ClientConn) ContactWriterClient {
	return &contactWriterClient{cc}
}

func (c *contactWriterClient) AddContact(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*RequestResponse, error) {
	out := new(RequestResponse)
	err := c.cc.Invoke(ctx, "/protocol.ContactWriter/AddContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactWriterClient) UpdateContact(ctx context.Context, in *Contact, opts ...grpc.CallOption) (*RequestResponse, error) {
	out := new(RequestResponse)
	err := c.cc.Invoke(ctx, "/protocol.ContactWriter/UpdateContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactWriterClient) DeleteContact(ctx context.Context, in *ContactReference, opts ...grpc.CallOption) (*RequestResponse, error) {
	out := new(RequestResponse)
	err := c.cc.Invoke(ctx, "/protocol.ContactWriter/DeleteContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactWriterServer is the server API for ContactWriter service.
type ContactWriterServer interface {
	AddContact(context.Context, *Contact) (*RequestResponse, error)
	UpdateContact(context.Context, *Contact) (*RequestResponse, error)
	DeleteContact(context.Context, *ContactReference) (*RequestResponse, error)
}

// UnimplementedContactWriterServer can be embedded to have forward compatible implementations.
type UnimplementedContactWriterServer struct {
}

func (*UnimplementedContactWriterServer) AddContact(ctx context.Context, req *Contact) (*RequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddContact not implemented")
}
func (*UnimplementedContactWriterServer) UpdateContact(ctx context.Context, req *Contact) (*RequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateContact not implemented")
}
func (*UnimplementedContactWriterServer) DeleteContact(ctx context.Context, req *ContactReference) (*RequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteContact not implemented")
}

func RegisterContactWriterServer(s *grpc.Server, srv ContactWriterServer) {
	s.RegisterService(&_ContactWriter_serviceDesc, srv)
}

func _ContactWriter_AddContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Contact)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactWriterServer).AddContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ContactWriter/AddContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactWriterServer).AddContact(ctx, req.(*Contact))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactWriter_UpdateContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Contact)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactWriterServer).UpdateContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ContactWriter/UpdateContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactWriterServer).UpdateContact(ctx, req.(*Contact))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactWriter_DeleteContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContactReference)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactWriterServer).DeleteContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ContactWriter/DeleteContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactWriterServer).DeleteContact(ctx, req.(*ContactReference))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContactWriter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.ContactWriter",
	HandlerType: (*ContactWriterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddContact",
			Handler:    _ContactWriter_AddContact_Handler,
		},
		{
			MethodName: "UpdateContact",
			Handler:    _ContactWriter_UpdateContact_Handler,
		},
		{
			MethodName: "DeleteContact",
			Handler:    _ContactWriter_DeleteContact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mycqrs.proto",
}

// ContactReaderClient is the client API for ContactReader service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContactReaderClient interface {
	GetContact(ctx context.Context, in *ContactReference, opts ...grpc.CallOption) (*ContactRequestResponse, error)
	ListContacts(ctx context.Context, in *ListContactsFilter, opts ...grpc.CallOption) (*ContactArrayRequestResponse, error)
}

type contactReaderClient struct {
	cc *grpc.ClientConn
}

func NewContactReaderClient(cc *grpc.ClientConn) ContactReaderClient {
	return &contactReaderClient{cc}
}

func (c *contactReaderClient) GetContact(ctx context.Context, in *ContactReference, opts ...grpc.CallOption) (*ContactRequestResponse, error) {
	out := new(ContactRequestResponse)
	err := c.cc.Invoke(ctx, "/protocol.ContactReader/GetContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contactReaderClient) ListContacts(ctx context.Context, in *ListContactsFilter, opts ...grpc.CallOption) (*ContactArrayRequestResponse, error) {
	out := new(ContactArrayRequestResponse)
	err := c.cc.Invoke(ctx, "/protocol.ContactReader/ListContacts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactReaderServer is the server API for ContactReader service.
type ContactReaderServer interface {
	GetContact(context.Context, *ContactReference) (*ContactRequestResponse, error)
	ListContacts(context.Context, *ListContactsFilter) (*ContactArrayRequestResponse, error)
}

// UnimplementedContactReaderServer can be embedded to have forward compatible implementations.
type UnimplementedContactReaderServer struct {
}

func (*UnimplementedContactReaderServer) GetContact(ctx context.Context, req *ContactReference) (*ContactRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContact not implemented")
}
func (*UnimplementedContactReaderServer) ListContacts(ctx context.Context, req *ListContactsFilter) (*ContactArrayRequestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListContacts not implemented")
}

func RegisterContactReaderServer(s *grpc.Server, srv ContactReaderServer) {
	s.RegisterService(&_ContactReader_serviceDesc, srv)
}

func _ContactReader_GetContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContactReference)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactReaderServer).GetContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ContactReader/GetContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactReaderServer).GetContact(ctx, req.(*ContactReference))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContactReader_ListContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContactsFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactReaderServer).ListContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.ContactReader/ListContacts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactReaderServer).ListContacts(ctx, req.(*ListContactsFilter))
	}
	return interceptor(ctx, in, info, handler)
}

var _ContactReader_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.ContactReader",
	HandlerType: (*ContactReaderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContact",
			Handler:    _ContactReader_GetContact_Handler,
		},
		{
			MethodName: "ListContacts",
			Handler:    _ContactReader_ListContacts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mycqrs.proto",
}
